### PR TITLE
DaisySP update and test

### PR DESCRIPTION
**Pull request by antisvin**
1. Updated DaisySP library from upstream
2. Added trivial test patch to confirm it's not broken
3. Added support for using it in native builds

### CODE REVIEW

**Comment by antisvin** [comment]
Will try to get upstream to use constant instead of std::sin(M_PI/4) to resolve this failure

**Comment by antisvin** [comment]
@mars we've quickly resolved the std::sin issue in upstream, so this is good to go.

**Comment by mars** [comment]
I'm not the `@mars` you're looking for.

**Comment by antisvin** [comment]
Sorry, I forgot how the internets work.

**Review by pingdynasty — APPROVED** [review]

**Pull request merged**
